/* eslint-disable @next/next/no-img-element */
import { Box, Grid } from "@mui/material";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import InstagramIcon from "@mui/icons-material/Instagram";
import GitHubIcon from "@mui/icons-material/GitHub";
import FacebookIcon from "@mui/icons-material/Facebook";

export default function Home() {
  return (
    <>
      <Head>
        <title>Material Art Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <Grid
          container
          gap={2}
          sx={{
            padding: {
              xs: "1rem",
              sm: "2rem",
              md: "4rem",
              minHeight: "100vh",
            },
          }}
        >
          <Grid item xs={12} md={5}>
            <p className={styles.header}>Material Art Practice</p>
            <div className={styles.lines} />
            <Box sx={{width: "100%", display: {xs: "flex", md: "block"}, marginTop: "3rem", alignItems: "flex-start", justifyContent: "space-between"}}>
              <p className={styles.text}>
                This is my most recent OC renderer material exercise. Microsoft
                materials work very well. I really want to study it. So some
                attempts were made. I hope you enjoy it.
              </p>
              <button className={styles.styledButton}>Get Started</button>
            </Box>
          </Grid>
          <Grid item xs={12} md={4}>
            <img
              src="/material1.png"
              alt="material1"
              className={styles.homeImage}
            />
          </Grid>
          <Grid item xs={12} md={4}>
            <Box className={styles.socialMedia}>
              <span>
                <LinkedInIcon />
              </span>
              <span>
                <InstagramIcon />
              </span>
              <span>
                <GitHubIcon />
              </span>
              <span>
                <FacebookIcon />
              </span>
            </Box>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
